# Generated by Django 6.0 on 2026-04-03 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustID', models.IntegerField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('CustomerDesc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('unit', models.CharField(blank=True, choices=[('ASMIPL', 'ASMIPL'), ('ASYM', 'ASYM')], max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'tbl_Customer',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dID', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=150, verbose_name='Department Name')),
                ('Deptdesc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('unit', models.CharField(blank=True, choices=[('ASMIPL', 'ASMIPL'), ('ASYM', 'ASYM')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'tbl_Department',
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('ASMIPL', 'ASMIPL'), ('ASYM', 'ASYM')], max_length=50)),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Machine Model Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machine Model',
                'verbose_name_plural': 'Machine Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, choices=[('ASMIPL', 'ASMIPL'), ('ASYM', 'ASYM')], max_length=150, null=True)),
                ('deptid', models.IntegerField(default=0, verbose_name='Department ID')),
                ('partid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Part ID')),
                ('partcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='Part Code')),
                ('partname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Part Name')),
                ('customerid', models.IntegerField(default=0, verbose_name='Customer ID')),
                ('projectid', models.IntegerField(default=0, verbose_name='Project ID')),
                ('process', models.CharField(max_length=200, verbose_name='Process Name / No.')),
                ('drawing', models.CharField(max_length=400, verbose_name='Drawing No.')),
                ('dotr', models.DateTimeField(verbose_name='Date of Tooling Required')),
                ('ncsno', models.CharField(blank=True, max_length=4000, null=True, verbose_name='NC Setup Sheet No(s)')),
                ('bqty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Batch Qty')),
                ('mfg', models.CharField(blank=True, max_length=4000, null=True, verbose_name='MR / PFD Sheet No(s)')),
                ('requestremarks', models.CharField(blank=True, max_length=550, null=True, verbose_name='Remarks')),
                ('mmodel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Machine Model')),
                ('typemachine', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of Machine')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('createdby', models.CharField(max_length=150, verbose_name='Created By')),
                ('statusremarks', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status Remarks')),
                ('shortclose', models.BooleanField(blank=True, null=True, verbose_name='Short Close')),
                ('cretedDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('istcmr', models.BooleanField(blank=True, null=True, verbose_name='Is TCMR')),
                ('req_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Draft Process Path')),
                ('mappprovedate', models.DateTimeField(blank=True, null=True, verbose_name='Manager Approve Date')),
                ('earlydatereason', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Early Date Reason')),
                ('aprrovedmanager', models.CharField(blank=True, max_length=150, null=True, verbose_name='Approved Manager')),
                ('isabsolute', models.BooleanField(blank=True, null=True, verbose_name='Is Absolute')),
                ('TINOs', models.CharField(blank=True, max_length=50, null=True, verbose_name='TINO(s)')),
            ],
            options={
                'verbose_name': 'PTR Request',
                'verbose_name_plural': 'PTR Requests',
                'ordering': ['-cretedDate'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('ASMIPL', 'ASMIPL'), ('ASYM', 'ASYM')], max_length=50)),
                ('type_of_machine', models.CharField(max_length=100, verbose_name='Type of Machine')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type of Machine',
                'verbose_name_plural': 'Types of Machine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('prjname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Project Name')),
                ('unit', models.CharField(blank=True, choices=[('ASMIPL', 'ASMIPL'), ('ASYM', 'ASYM')], max_length=100, null=True)),
                ('custid', models.ForeignKey(db_column='custid', on_delete=django.db.models.deletion.CASCADE, to='ptr_app.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'tbl_Project',
            },
        ),
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('PartID', models.AutoField(primary_key=True, serialize=False)),
                ('PartName', models.CharField(max_length=150, verbose_name='Part No. / Code')),
                ('PartDesc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Part Description')),
                ('unit', models.CharField(blank=True, choices=[('ASMIPL', 'ASMIPL'), ('ASYM', 'ASYM')], max_length=150, null=True)),
                ('PrjID', models.ForeignKey(db_column='PrjID', on_delete=django.db.models.deletion.CASCADE, to='ptr_app.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'tbl_Parts',
            },
        ),
    ]
