# Generated by Django 6.0 on 2026-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMapping',
            fields=[
                ('RowId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpNumber', models.CharField(max_length=50, verbose_name='Employee Number')),
                ('EmpMail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Email')),
                ('Status', models.CharField(blank=True, default='Active', max_length=50, null=True, verbose_name='Status')),
                ('Role', models.CharField(blank=True, choices=[('PTR Requester', 'PTR Requester'), ('Approver', 'Approver'), ('Designer', 'Designer'), ('ToolingExecutive', 'Tooling Executive'), ('ToolRoom', 'Tool Room'), ('Admin', 'Admin'), ('SystemAdmin', 'System Admin'), ('PM', 'PM')], max_length=50, null=True, verbose_name='Role')),
                ('Unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('AddedBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('DateTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added Date')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modified By')),
                ('ModifyDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Employee Mapping',
                'verbose_name_plural': 'Employee Mappings',
                'db_table': 'tbl_EmployeeMapping',
            },
        ),
    ]
