# Generated by Django 6.0 on 2026-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0002_employeemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormMapping',
            fields=[
                ('RowId', models.AutoField(primary_key=True, serialize=False)),
                ('FormID', models.IntegerField(blank=True, null=True, verbose_name='Form ID')),
                ('RolID', models.IntegerField(blank=True, null=True, verbose_name='Role ID')),
                ('IsActive', models.BooleanField(blank=True, null=True, verbose_name='Is Active')),
                ('AddedBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='Added By')),
                ('DateCreated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'Form Mapping',
                'verbose_name_plural': 'Form Mappings',
                'db_table': 'tbl_FormMapping',
            },
        ),
        migrations.CreateModel(
            name='FormMaster',
            fields=[
                ('RowID', models.AutoField(primary_key=True, serialize=False)),
                ('FormName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Form Name')),
                ('FormID', models.IntegerField(verbose_name='Form ID')),
            ],
            options={
                'verbose_name': 'Form Master',
                'verbose_name_plural': 'Form Masters',
                'db_table': 'tbl_FormMaster',
            },
        ),
    ]
