# Generated by Django 6.0 on 2026-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0003_formmapping_formmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtrAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptrno', models.CharField(max_length=150, verbose_name='PTR Number')),
                ('desginer', models.CharField(max_length=150, verbose_name='Designer')),
                ('pldstartdate', models.DateTimeField(blank=True, null=True, verbose_name='Planned Start Date')),
                ('pldcompdate', models.DateTimeField(verbose_name='Planned Completion Date')),
                ('remarks', models.CharField(blank=True, max_length=150, null=True, verbose_name='Remarks')),
                ('shortclose', models.BooleanField(blank=True, null=True, verbose_name='Short Close')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='Status')),
                ('ptrid', models.IntegerField(verbose_name='PTR Request ID')),
                ('plannedHour', models.IntegerField(blank=True, null=True, verbose_name='Planned Hours')),
            ],
            options={
                'verbose_name': 'PTR Admin',
                'verbose_name_plural': 'PTR Admin Entries',
                'db_table': 'Tbl_ptrAdmin',
            },
        ),
    ]
