# Generated by Django 6.0 on 2026-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0004_ptradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptrrequest',
            name='ptrno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='PTR Number'),
        ),
    ]
