# Generated by Django 6.0 on 2026-04-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0005_ptrrequest_ptrno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalSpares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TINO', models.CharField(blank=True, max_length=950, null=True, verbose_name='TINO')),
                ('drgNO', models.CharField(blank=True, max_length=950, null=True, verbose_name='Drawing No')),
                ('cmcode', models.CharField(blank=True, max_length=950, null=True, verbose_name='CM Code')),
                ('ptrid', models.IntegerField(blank=True, null=True, verbose_name='PTR Request ID')),
                ('mprno', models.CharField(blank=True, max_length=550, null=True, verbose_name='MPR No')),
            ],
            options={
                'verbose_name': 'Critical Spare',
                'verbose_name_plural': 'Critical Spares',
                'db_table': 'tbl_CriticalSpares',
            },
        ),
        migrations.CreateModel(
            name='DesignerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptrid', models.IntegerField(verbose_name='PTR Request ID')),
                ('ASD', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Date')),
                ('ACD', models.DateTimeField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('DescTooling', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description of Tooling')),
                ('TINo', models.CharField(blank=True, max_length=50, null=True, verbose_name='TINO')),
                ('ECost', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimated Cost')),
                ('Path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Path in CM')),
                ('ToolMaterial', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tool/Fixture Material')),
                ('toollife', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tool Life')),
                ('PMFrequency', models.IntegerField(blank=True, null=True, verbose_name='PM Frequency / yr')),
                ('actualHr', models.IntegerField(blank=True, null=True, verbose_name='Actual Hours')),
                ('desremarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Designer Remarks')),
                ('isinhous', models.BooleanField(blank=True, null=True, verbose_name='Aequs Inhouse')),
                ('isVoiceSetup', models.BooleanField(blank=True, null=True, verbose_name='Vice Setup')),
                ('chk_jaw', models.BooleanField(blank=True, null=True, verbose_name='Turning Jaw Setup')),
                ('iscmc', models.BooleanField(blank=True, null=True, verbose_name='Critical Spares Required')),
                ('cmpath', models.CharField(blank=True, max_length=600, null=True, verbose_name='CM Path')),
                ('mprDate', models.DateTimeField(blank=True, null=True, verbose_name='MPR Date')),
                ('MPRNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='MPR Number')),
                ('suplier', models.CharField(blank=True, max_length=150, null=True, verbose_name='Supplier')),
                ('pocost', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actual Cost as per PO')),
                ('eddate', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('consumablecode', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fixed Asset Code')),
                ('roino', models.CharField(blank=True, max_length=300, null=True, verbose_name='ROI / WBS')),
                ('waitingroi', models.BooleanField(blank=True, null=True, verbose_name='Waiting for ROI No.')),
                ('Tfeedback', models.CharField(blank=True, max_length=200, null=True, verbose_name='Trial Feedback Report No.')),
                ('tvdate', models.DateTimeField(blank=True, null=True, verbose_name='TV Date')),
                ('bitfinance', models.BooleanField(blank=True, null=True)),
                ('bitSCM', models.BooleanField(blank=True, null=True)),
                ('biterp', models.BooleanField(blank=True, null=True)),
                ('bitCM', models.BooleanField(blank=True, null=True)),
                ('bitvreport', models.BooleanField(blank=True, null=True)),
                ('bitTfeedback', models.BooleanField(blank=True, null=True)),
                ('statusFeedBack', models.CharField(blank=True, max_length=200, null=True)),
                ('pathtomaster', models.CharField(blank=True, max_length=300, null=True)),
                ('erpcode', models.CharField(blank=True, max_length=200, null=True)),
                ('bitcommon', models.BooleanField(blank=True, null=True)),
                ('commonremarks', models.CharField(blank=True, max_length=250, null=True)),
                ('commonptrid', models.IntegerField(blank=True, null=True)),
                ('latereason', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('ToolLifeModifiedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('ToolLifeModifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Designer Entry',
                'verbose_name_plural': 'Designer Entries',
                'db_table': 'tbl_designer',
            },
        ),
    ]
