# Generated by Django 6.0 on 2026-04-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0006_criticalspares_designerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalspares',
            name='UOM',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='UOM'),
        ),
        migrations.AddField(
            model_name='criticalspares',
            name='desc',
            field=models.CharField(blank=True, max_length=950, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='criticalspares',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='criticalspares',
            name='cmcode',
            field=models.CharField(blank=True, max_length=950, null=True, verbose_name='Consumable Code'),
        ),
        migrations.AlterField(
            model_name='criticalspares',
            name='drgNO',
            field=models.CharField(blank=True, max_length=950, null=True, verbose_name='Drawing Number'),
        ),
    ]
