# Generated by Django 6.0 on 2026-04-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0007_criticalspares_uom_criticalspares_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalspares',
            name='ptrid',
        ),
        migrations.RemoveField(
            model_name='designerentry',
            name='ptrid',
        ),
        migrations.RemoveField(
            model_name='ptradmin',
            name='ptrid',
        ),
        migrations.AddField(
            model_name='criticalspares',
            name='ptr',
            field=models.ForeignKey(blank=True, db_column='ptrid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='critical_spares', to='ptr_app.ptrrequest', verbose_name='PTR Request'),
        ),
        migrations.AddField(
            model_name='designerentry',
            name='ptr',
            field=models.ForeignKey(db_column='ptrid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designer_entries', to='ptr_app.ptrrequest', verbose_name='PTR Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptradmin',
            name='ptr',
            field=models.ForeignKey(db_column='ptrid', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_entries', to='ptr_app.ptrrequest', verbose_name='PTR Request'),
            preserve_default=False,
        ),
    ]
