# Generated by Django 6.0 on 2026-04-14 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0008_remove_criticalspares_ptrid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcvdate', models.DateTimeField(verbose_name='Receiving Date')),
                ('tvrn', models.CharField(max_length=250, verbose_name='Tooling Verification Report Number')),
                ('grndate', models.DateTimeField(blank=True, null=True, verbose_name='GRN Date')),
                ('grnno', models.CharField(blank=True, max_length=500, null=True, verbose_name='GRN Number')),
                ('ModifiedBy', models.CharField(blank=True, max_length=30, null=True, verbose_name='Modified By')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('Approver', models.IntegerField(blank=True, null=True, verbose_name='Approver')),
                ('ptr', models.ForeignKey(db_column='ptrid', on_delete=django.db.models.deletion.CASCADE, related_name='receiving_entries', to='ptr_app.ptrrequest', verbose_name='PTR Request')),
            ],
            options={
                'verbose_name': 'Receiving Entry',
                'verbose_name_plural': 'Receiving Entries',
                'db_table': 'tbl_receiving',
            },
        ),
    ]
