# Generated by Django 6.0 on 2026-04-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0009_receivingentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptrrequest',
            name='isabsolute',
        ),
        migrations.AddField(
            model_name='ptrrequest',
            name='isobsolete',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Obsolete'),
        ),
        migrations.CreateModel(
            name='TblRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisionNo', models.IntegerField(default=0, verbose_name='Revision Number')),
                ('DescriptionRev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Reason For Obsolete')),
                ('Approver', models.CharField(blank=True, max_length=250, null=True, verbose_name='Approver')),
                ('Vdate', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('ToolMod', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tool Modification')),
                ('isapproved', models.BooleanField(blank=True, null=True, verbose_name='Is Approved')),
                ('RemarksDisposition', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks on Disposition')),
                ('ptr', models.ForeignKey(db_column='ptrid', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='ptr_app.ptrrequest', verbose_name='PTR Request')),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'db_table': 'tbl_revision',
            },
        ),
    ]
