# Generated by Django 6.0 on 2026-04-21 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0010_remove_ptrrequest_isabsolute_ptrrequest_isobsolete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmdate', models.DateField(verbose_name='Plan Date for Inspection')),
                ('pmreportno', models.CharField(max_length=150, verbose_name='Report No.')),
                ('actualdate', models.DateField(verbose_name='Actual Date')),
                ('rmk', models.CharField(max_length=250, verbose_name='Remarks')),
                ('inspector', models.CharField(blank=True, max_length=250, null=True, verbose_name='Inspector')),
                ('Approver', models.CharField(blank=True, max_length=250, null=True, verbose_name='Approver')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('TINO', models.CharField(blank=True, max_length=250, null=True, verbose_name='TINO')),
                ('ptr', models.ForeignKey(db_column='ptrid', on_delete=django.db.models.deletion.CASCADE, related_name='preventative_maintenances', to='ptr_app.ptrrequest', verbose_name='PTR Request')),
            ],
            options={
                'verbose_name': 'Preventive Maintenance',
                'verbose_name_plural': 'Preventive Maintenances',
                'db_table': 'tbl_preventM',
            },
        ),
    ]
