# Generated by Django 6.0 on 2026-04-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0011_preventm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tino', models.CharField(blank=True, max_length=500, null=True, verbose_name='TINO')),
                ('bd_date', models.DateField(blank=True, null=True, verbose_name='Breakdown Date')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='Reason')),
                ('reportNo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Report No')),
                ('Status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('downtime', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Downtime')),
                ('Approved', models.CharField(blank=True, max_length=50, null=True, verbose_name='Approved By')),
                ('ptr', models.ForeignKey(db_column='ptrid', on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='ptr_app.ptrrequest', verbose_name='PTR Request')),
            ],
            options={
                'verbose_name': 'Breakdown Maintenance',
                'verbose_name_plural': 'Breakdown Maintenances',
                'db_table': 'tbl_breakdown',
            },
        ),
    ]
