# Generated by Django 6.0 on 2026-04-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptr_app', '0012_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLifeExtend',
            fields=[
                ('RowID', models.AutoField(primary_key=True, serialize=False)),
                ('PTRNo', models.CharField(blank=True, max_length=50, null=True)),
                ('TiNo', models.CharField(max_length=50)),
                ('ToolMaterial', models.CharField(blank=True, max_length=250, null=True)),
                ('InspectionReportNo', models.CharField(max_length=50)),
                ('PreviousToolExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('ToolLifeExtendedYr', models.IntegerField()),
                ('ExtendedOn', models.DateTimeField()),
                ('Remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('ApprovedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('InspectedBy', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Unit', models.CharField(blank=True, max_length=50, null=True)),
                ('PTRId', models.ForeignKey(db_column='PTRId', on_delete=django.db.models.deletion.CASCADE, related_name='tool_extensions', to='ptr_app.ptrrequest')),
            ],
            options={
                'verbose_name': 'Tool Life Extension',
                'verbose_name_plural': 'Tool Life Extensions',
                'db_table': 'Tbl_ToolLifeExtend',
            },
        ),
    ]
